"""add read-only CRM synchronization and MAWB domain

Revision ID: 20260715_0002
Revises: 20260714_0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="20260715_0002"; down_revision="20260714_0001"; branch_labels=None; depends_on=None
UUID=postgresql.UUID(as_uuid=True); TZ=sa.DateTime(timezone=True)

def upgrade():
    # The original initial revision used the live SQLAlchemy metadata rather
    # than a frozen schema snapshot. On a brand-new database that metadata may
    # already contain this revision's tables and columns. Complete only the
    # revision-specific views in that case; established 0001 databases still
    # follow the normal additive migration below.
    if sa.inspect(op.get_bind()).has_table('crm_sync_runs'):
        op.execute('DROP VIEW IF EXISTS vw_company_operational_summary')
        op.execute("""CREATE VIEW vw_company_operational_summary AS SELECT c.id company_id,c.icris_number,c.company_name,c.status company_status,c.is_provisional,c.crm_last_synced_at,count(DISTINCT s.id)::int shipment_count,count(DISTINCT p.id)::int package_count,count(DISTINCT s.id) FILTER(WHERE s.match_status IN ('matched','manually_linked'))::int matched_shipment_count,count(DISTINCT s.id) FILTER(WHERE s.match_status='suggested')::int suggested_shipment_count,0::int unmatched_shipment_count,max(s.shipment_date) last_shipment_date,max(s.created_at) last_imported_at,count(DISTINCT d.id)::int document_count,count(DISTINCT d.id) FILTER(WHERE d.status='active')::int active_document_count,count(DISTINCT s.id) FILTER(WHERE s.name_mismatch)::int name_mismatch_count FROM companies c LEFT JOIN shipments s ON s.company_id=c.id LEFT JOIN packages p ON p.shipment_id=s.id LEFT JOIN company_documents d ON d.company_id=c.id GROUP BY c.id""")
        op.execute("""CREATE VIEW vw_mawb_reconciliation AS SELECT m.id mawb_id,m.mawb_number,m.manifest_date,count(s.id)::int shipment_count,count(DISTINCT s.company_id)::int customer_count,count(s.id) FILTER(WHERE s.source_icris_number IS NULL OR btrim(s.source_icris_number)='')::int missing_icris_count,sum(s.pieces) row_pieces,sum(s.actual_weight) row_actual_weight,(coalesce(m.pp_pieces,0)+coalesce(m.fc_pieces,0)+coalesce(m.fd_pieces,0))-coalesce(sum(s.pieces),0) pieces_difference FROM master_air_waybills m LEFT JOIN shipments s ON s.mawb_id=m.id GROUP BY m.id""")
        op.execute("""CREATE VIEW vw_crm_sync_quality AS SELECT id sync_run_id,status,created_at,completed_at,mawbs_found,shipments_found,matched_by_icris,missing_icris,warnings_count,failed_count FROM crm_sync_runs""")
        op.execute("""CREATE VIEW vw_customer_name_quality AS SELECT c.id company_id,c.icris_number,c.company_name,count(s.id) FILTER(WHERE s.name_mismatch)::int mismatch_count,count(s.id)::int shipment_count FROM companies c LEFT JOIN shipments s ON s.company_id=c.id GROUP BY c.id""")
        return
    op.add_column('companies',sa.Column('is_provisional',sa.Boolean(),nullable=False,server_default=sa.false()))
    op.add_column('companies',sa.Column('crm_customer_id',sa.String(),nullable=True)); op.create_index('ix_companies_crm_customer_id','companies',['crm_customer_id'])
    op.add_column('companies',sa.Column('crm_last_synced_at',TZ,nullable=True)); op.add_column('companies',sa.Column('name_source',sa.String(),nullable=True))
    op.create_index('uq_companies_icris_normalized','companies',[sa.text('lower(btrim(icris_number))')],unique=True)
    op.create_table('master_air_waybills',sa.Column('id',UUID,primary_key=True),sa.Column('mawb_number',sa.String(),nullable=False),sa.Column('manifest_date',sa.Date(),nullable=False),sa.Column('flight_number',sa.String()),sa.Column('origin',sa.String()),sa.Column('destination',sa.String()),sa.Column('exchange_rate',sa.Numeric(18,6)),sa.Column('fuel_surcharge',sa.Numeric(18,6)),sa.Column('pp_weight',sa.Numeric(16,3)),sa.Column('fc_weight',sa.Numeric(16,3)),sa.Column('fd_weight',sa.Numeric(16,3)),sa.Column('pp_pieces',sa.Integer()),sa.Column('fc_pieces',sa.Integer()),sa.Column('fd_pieces',sa.Integer()),sa.Column('pp_bill_amount',sa.Numeric(18,2)),sa.Column('fc_bill_amount',sa.Numeric(18,2)),sa.Column('fd_bill_amount',sa.Numeric(18,2)),sa.Column('pp_gross_amount',sa.Numeric(18,2)),sa.Column('fc_gross_amount',sa.Numeric(18,2)),sa.Column('fd_gross_amount',sa.Numeric(18,2)),sa.Column('source_system',sa.String(),nullable=False,server_default='crm'),sa.Column('source_key',sa.String()),sa.Column('source_url',sa.Text()),sa.Column('source_checksum',sa.String()),sa.Column('last_synced_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('created_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('updated_at',TZ,nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('mawb_number','manifest_date',name='uq_mawb_number_date'))
    for col in ['mawb_number','manifest_date','flight_number','origin','destination','source_checksum']: op.create_index(f'ix_master_air_waybills_{col}','master_air_waybills',[col])
    shipment_cols=[sa.Column('mawb_id',UUID,sa.ForeignKey('master_air_waybills.id')),sa.Column('source_icris_number',sa.String()),sa.Column('source_customer_name',sa.String()),sa.Column('crm_source_key',sa.String()),sa.Column('crm_source_url',sa.Text()),sa.Column('crm_last_synced_at',TZ),sa.Column('actual_weight',sa.Numeric(16,3)),sa.Column('dimensional_weight',sa.Numeric(16,3)),sa.Column('pay_term',sa.String()),sa.Column('bill_number',sa.String()),sa.Column('bill_amount',sa.Numeric(18,2)),sa.Column('gross_amount',sa.Numeric(18,2)),sa.Column('tariff_rate',sa.Numeric(18,6)),sa.Column('ae_code',sa.String()),sa.Column('delivery_code',sa.String()),sa.Column('name_mismatch',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('is_manually_matched',sa.Boolean(),nullable=False,server_default=sa.false())]
    for c in shipment_cols: op.add_column('shipments',c)
    op.execute('UPDATE shipments SET is_manually_matched=manually_matched')
    for col in ['mawb_id','source_icris_number','crm_source_key','pay_term','bill_number']: op.create_index(f'ix_shipments_{col}','shipments',[col])
    op.create_table('crm_sync_runs',sa.Column('id',UUID,primary_key=True),sa.Column('sync_type',sa.String(),nullable=False),sa.Column('status',sa.String(),nullable=False,server_default='queued'),sa.Column('requested_from_date',sa.Date()),sa.Column('requested_to_date',sa.Date()),sa.Column('requested_mawb',sa.String()),sa.Column('started_at',TZ),sa.Column('completed_at',TZ),*[sa.Column(x,sa.Integer(),nullable=False,server_default='0') for x in ['list_pages_read','detail_pages_read','mawbs_found','mawbs_created','mawbs_updated','shipments_found','shipments_created','shipments_updated','companies_created','companies_updated','matched_by_icris','missing_icris','warnings_count','failed_count']],sa.Column('error_message',sa.Text()),sa.Column('worker_id',sa.String()),sa.Column('created_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('updated_at',TZ,nullable=False,server_default=sa.func.now()))
    op.create_index('ix_crm_sync_runs_status','crm_sync_runs',['status'])
    op.create_table('crm_sync_state',sa.Column('id',UUID,primary_key=True),sa.Column('entity_type',sa.String(),nullable=False,unique=True),sa.Column('last_successful_date',sa.Date()),sa.Column('last_successful_sync_at',TZ),sa.Column('last_sync_run_id',UUID,sa.ForeignKey('crm_sync_runs.id')),sa.Column('cursor_json',postgresql.JSONB()),sa.Column('updated_at',TZ,nullable=False,server_default=sa.func.now()))
    op.create_table('crm_raw_manifest_headers',sa.Column('id',UUID,primary_key=True),sa.Column('sync_run_id',UUID,sa.ForeignKey('crm_sync_runs.id'),nullable=False),sa.Column('master_air_waybill_id',UUID,sa.ForeignKey('master_air_waybills.id')),sa.Column('mawb_number',sa.String()),sa.Column('manifest_date',sa.Date()),sa.Column('source_url',sa.Text()),sa.Column('source_headers_json',postgresql.JSONB(),nullable=False),sa.Column('raw_values_json',postgresql.JSONB(),nullable=False),sa.Column('source_checksum',sa.String(),nullable=False),sa.Column('processing_status',sa.String(),nullable=False),sa.Column('warning_messages',postgresql.JSONB()),sa.Column('error_message',sa.Text()),sa.Column('created_at',TZ,nullable=False,server_default=sa.func.now()))
    op.create_index('ix_crm_raw_manifest_headers_sync_run_id','crm_raw_manifest_headers',['sync_run_id']); op.create_index('ix_crm_raw_manifest_headers_source_checksum','crm_raw_manifest_headers',['source_checksum'])
    op.create_table('crm_raw_manifest_rows',sa.Column('id',UUID,primary_key=True),sa.Column('sync_run_id',UUID,sa.ForeignKey('crm_sync_runs.id'),nullable=False),sa.Column('master_air_waybill_id',UUID,sa.ForeignKey('master_air_waybills.id')),sa.Column('shipment_id',UUID,sa.ForeignKey('shipments.id')),sa.Column('source_row_number',sa.Integer(),nullable=False),sa.Column('tracking_number',sa.String()),sa.Column('source_icris_number',sa.String()),sa.Column('source_headers_json',postgresql.JSONB(),nullable=False),sa.Column('raw_values_json',postgresql.JSONB(),nullable=False),sa.Column('source_checksum',sa.String(),nullable=False),sa.Column('processing_status',sa.String(),nullable=False),sa.Column('warning_messages',postgresql.JSONB()),sa.Column('error_message',sa.Text()),sa.Column('created_at',TZ,nullable=False,server_default=sa.func.now()))
    for col in ['sync_run_id','tracking_number','source_icris_number','source_checksum']: op.create_index(f'ix_crm_raw_manifest_rows_{col}','crm_raw_manifest_rows',[col])
    op.create_table('data_quality_issues',sa.Column('id',UUID,primary_key=True),sa.Column('issue_type',sa.String(),nullable=False),sa.Column('severity',sa.String(),nullable=False),sa.Column('company_id',UUID,sa.ForeignKey('companies.id')),sa.Column('shipment_id',UUID,sa.ForeignKey('shipments.id')),sa.Column('mawb_id',UUID,sa.ForeignKey('master_air_waybills.id')),sa.Column('sync_run_id',UUID,sa.ForeignKey('crm_sync_runs.id')),sa.Column('source_icris_number',sa.String()),sa.Column('source_company_name',sa.String()),sa.Column('details_json',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('status',sa.String(),nullable=False,server_default='open'),sa.Column('first_seen_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('last_seen_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('resolved_at',TZ),sa.Column('created_at',TZ,nullable=False,server_default=sa.func.now()),sa.Column('updated_at',TZ,nullable=False,server_default=sa.func.now()))
    op.create_index('ix_data_quality_issues_issue_type','data_quality_issues',['issue_type']); op.create_index('ix_data_quality_issues_status','data_quality_issues',['status'])
    op.execute('DROP VIEW vw_company_operational_summary')
    op.execute("""CREATE VIEW vw_company_operational_summary AS SELECT c.id company_id,c.icris_number,c.company_name,c.status company_status,c.is_provisional,c.crm_last_synced_at,count(DISTINCT s.id)::int shipment_count,count(DISTINCT p.id)::int package_count,count(DISTINCT s.id) FILTER(WHERE s.match_status IN ('matched','manually_linked'))::int matched_shipment_count,count(DISTINCT s.id) FILTER(WHERE s.match_status='suggested')::int suggested_shipment_count,0::int unmatched_shipment_count,max(s.shipment_date) last_shipment_date,max(s.created_at) last_imported_at,count(DISTINCT d.id)::int document_count,count(DISTINCT d.id) FILTER(WHERE d.status='active')::int active_document_count,count(DISTINCT s.id) FILTER(WHERE s.name_mismatch)::int name_mismatch_count FROM companies c LEFT JOIN shipments s ON s.company_id=c.id LEFT JOIN packages p ON p.shipment_id=s.id LEFT JOIN company_documents d ON d.company_id=c.id GROUP BY c.id""")
    op.execute("""CREATE VIEW vw_mawb_reconciliation AS SELECT m.id mawb_id,m.mawb_number,m.manifest_date,count(s.id)::int shipment_count,count(DISTINCT s.company_id)::int customer_count,count(s.id) FILTER(WHERE s.source_icris_number IS NULL OR btrim(s.source_icris_number)='')::int missing_icris_count,sum(s.pieces) row_pieces,sum(s.actual_weight) row_actual_weight,(coalesce(m.pp_pieces,0)+coalesce(m.fc_pieces,0)+coalesce(m.fd_pieces,0))-coalesce(sum(s.pieces),0) pieces_difference FROM master_air_waybills m LEFT JOIN shipments s ON s.mawb_id=m.id GROUP BY m.id""")
    op.execute("""CREATE VIEW vw_crm_sync_quality AS SELECT id sync_run_id,status,created_at,completed_at,mawbs_found,shipments_found,matched_by_icris,missing_icris,warnings_count,failed_count FROM crm_sync_runs""")
    op.execute("""CREATE VIEW vw_customer_name_quality AS SELECT c.id company_id,c.icris_number,c.company_name,count(s.id) FILTER(WHERE s.name_mismatch)::int mismatch_count,count(s.id)::int shipment_count FROM companies c LEFT JOIN shipments s ON s.company_id=c.id GROUP BY c.id""")

def downgrade():
    op.execute('DROP VIEW IF EXISTS vw_customer_name_quality'); op.execute('DROP VIEW IF EXISTS vw_crm_sync_quality'); op.execute('DROP VIEW IF EXISTS vw_mawb_reconciliation')
    raise RuntimeError('CRM migration downgrade is intentionally disabled to protect synchronized and existing data')
